"===========
" Vi compatability breakers
"===========
" https://superuser.com/a/603928
set nocompatible
filetype plugin on
set modeline

"===========
" Basics
"===========
" Show line numbers
set number
" Turn on syntax highlighting
syntax on
" Allow backspacing over:
"	- indent
"	- linebreaks
"	- start of insert
set backspace=indent,eol,start

"===========
" Indentation
"===========
" Auto indent
set smartindent
" Explicitly use tabs
set noexpandtab
" Dislpay tab as 4 spaces
set tabstop=2
set shiftwidth=2

"===========
" Mouse
"===========
" Allow mouse usage
set mouse=a
" Set ttymouse type
if has("mouse_sgr")
	set ttymouse=sgr
else
	set ttymouse=xterm2
end

" FUNCTIONS
source $HOME/.dotfiles/vim/vimrc.d/functions.vimrc
" PLUGIN
source $HOME/.dotfiles/vim/vimrc.d/plugin.vimrc
" BINDS
source $HOME/.dotfiles/vim/vimrc.d/binds.vimrc
" LEADER
source $HOME/.dotfiles/vim/vimrc.d/leader.vimrc
" VISUAL
source $HOME/.dotfiles/vim/vimrc.d/visual.vimrc
" ABBREVIATE
source $HOME/.dotfiles/vim/vimrc.d/abbreviate.vimrc

" Add auto close of terminal
"augroup terminal
				"autocmd!
				"autocmd TermClose * if getline('$') == 'Exit 0' | close | endif
"augroup end
