#!/usr/bin/env bash
# vim: set filetype=sh :

#==========
# Directory locations
#==========
DOTFILES_DIR=~/.dotfiles
BASH_DIR=$DOTFILES_DIR/bash

#==========
# Default .bashrc functionality
#==========
# If not running interactively, don't do anything
# https://unix.stackexchange.com/a/257613
case $- in
	*i*)
		;;
	*)
		return
		;;
esac

# Check window size after each command.
# Update LINES and COLUMNS if nedded.
shopt -s checkwinsize

# Recursive double-wildcard (**)
shopt -s globstar

# Better less for non-text input files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

#==========
# Disable <C-s>
#==========
bind -r "C-s"
stty -ixon

#==========
# Editor
#==========
# If Vim is installed, set as default editor
# https://unix.stackexchange.com/a/73486

# Attempt to fetch path to Vim
path_to_vim=$(command -v vim)
# Verify path_to_vim leads to an executable
if [ -x "$path_to_vim" ]; then
	export VISUAL=$path_to_vim
	export EDITOR=$path_to_vim
fi

#==========
# Load files
#==========
bashrcFiles=(
	color
	prompt
	history
	completion
)
for file in "${bashrcFiles[@]}"; do
	. $BASH_DIR/bashrc.d/$file.sh
done

#==========
# Private / machine specific
#==========
for file in $BASH_DIR/private.d/*.sh; do
	[ -r "$file" ] && [ -f "$file" ] && . "$file"
done
