# vim: set filetype=sh :

#==========
# Colorize
#==========
# https://superuser.com/a/879035
export CLICOLOR=1 # for *BSD/darwin
ls --color=auto &> /dev/null && alias ls="ls --color=auto" ||

alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

#==========
# Extend ls
#==========
alias ll="ls -alF"
alias la="ls -A"
alias l="ls -CF"
